#!/bin/bash

sudo apt-get install qt5-default qt5-qmake
qmake calc.pro
echo '[Desktop Entry]
Name=OIcalc
Comment=A Simple Calculator For OIer
Exec="~/.local/bin/OIcalc"
Terminal=false
Type=Application
Icon=~/.local/share/icons/OIcalc/OIcalc.ico
Categories=Development;' > ~/.local/share/applications/OIcalc.desktop
make
mkdir -p ~/.local
mkdir -p ~/.local/share
mkdir -p ~/.local/share/icons
mkdir -p ~/.local/share/icons/OIcalc
mkdir -p ~/.local/bin
cp ./OIcalc.ico ~/.local/share/icons/OIcalc/
cp ./OIcalc ~/.local/bin/
