#!/bin/bash

sudo apt-get install qt5-default qt5-qmake
qmake calc.pro
echo '[Desktop Entry]
Name=OIcalc
Comment=A Simple Calculator For OIer
Exec="~/.local/bin/OIcalc"
Terminal=false
Type=Application
Icon=~/.local/share/icons/OIcalc.ico
Categories=Development;' > ~/.local/share/applications/OIcalc.desktop
make
mkdir ~/.local/share/icons/OIcalc
cp ./OIcalc.ico ~/.local/share/icons/OIcalc/OIcalc.ico
cp ./OIcalc ~/.local/bin/OIcalc
